global:
  scrape_interval:     5s # Default is 1m
  evaluation_interval: 1m # Default

scrape_configs:
- job_name: 'cadvisor'
  static_configs:
    - targets: ['cadvisor:8080', 'localhost:8081']

- job_name: 'occupation-crawler'
  static_configs:
    - targets: ['occupation-crawler:8080', 'localhost:8082']

- job_name: 'node-exporter'
  static_configs:
    - targets: ['node-exporter:9100','localhost:9101']
